### Dodanie nowego produktu
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "Klawiatura Mechaniczna",
  "sku": "KLA-LOG-001",
  "description": "Klawiatura bezprzewodowa przełączniki Tactile",
  "price": 450.00,
  "quantity": 15
}

###
### Pobranie wszystkich produktów
GET http://localhost:8080/api/products